name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .deno-version)" >> $GITHUB_ENV
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.deno-version', 'deno.lock') }}
      - name: Check docs
        run:
          deno task docs:rules
          git diff --exit-code
      - name: Run linters
        run:
          deno task check
      - name: Run unit tests
        run:
          deno task test
      - name: Run e2e tests
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          NO_COLOR=1 deno task test:e2e 2>> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: deno publish --dry-run
        run:
          deno publish --dry-run
