name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: e94581d272d842ac9d2da9cab8bc9edf4c3170e6
      - name: Run linters
        run:
          deno task check
      - name: Run tests
        run:
          deno task test
