name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: 5194222e02d54158c47240ef78f7d3379a274eeb
      - name: Run linters
        run:
          deno task check
      - name: Run tests
        run:
          deno task test
